const TABLE = {
    'IRL': {
        'options': [
            'Low',
            'Normal',
            'Good',
            'Very Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '720',
            'framerate': 30,
            'avgBitrate': 3000,
            'maxBitrate': null,
        },
        'Normal': {
            'resolution': '720',
            'framerate': 40,
            'avgBitrate': 3500,
            'maxBitrate': null,
        },
        'Good': {
            'resolution': '1080',
            'framerate': 40,
            'avgBitrate': 4500,
            'maxBitrate': null,
        },
        'Very Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 6000,
            'maxBitrate': null,
        },
    },
    'Text': {
        'options': [
            'Low',
            'Normal',
            'Good',
            'Very Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '1080',
            'framerate': 30,
            'avgBitrate': 1000,
            'maxBitrate': 2000,
        },
        'Normal': {
            'resolution': '1080',
            'framerate': 30,
            'avgBitrate': 2000,
            'maxBitrate': 3000,
        },
        'Good': {
            'resolution': '1080',
            'framerate': 40,
            'avgBitrate': 2500,
            'maxBitrate': 3500,
        },
        'Very Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 3500,
            'maxBitrate': 4000,
        },
    },
    'Pixel': {
        'options': [
            'Low',
            'Normal',
            'Good',
            'Very Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '720',
            'framerate': 30,
            'avgBitrate': 1500,
            'maxBitrate': 3000,
        },
        'Normal': {
            'resolution': '720',
            'framerate': 40,
            'avgBitrate': 2000,
            'maxBitrate': 3500,
        },
        'Good': {
            'resolution': '720',
            'framerate': 60,
            'avgBitrate': 3500,
            'maxBitrate': 4500,
        },
        'Very Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 4000,
            'maxBitrate': 5500,
        },
    },
    '2D': {
        'options': [
            'Low',
            'Normal',
            'Good',
            'Very Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '720',
            'framerate': 40,
            'avgBitrate': 3000,
            'maxBitrate': 4500,
        },
        'Normal': {
            'resolution': '720',
            'framerate': 60,
            'avgBitrate': 3500,
            'maxBitrate': 5000,
        },
        'Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 4500,
            'maxBitrate': 6000,
        },
        'Very Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 6500,
            'maxBitrate': 7500,
        },
    },
    'TopDown': {
        'options': [
            'Low',
            'Normal',
            'Good',
            'Very Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '720',
            'framerate': 40,
            'avgBitrate': 3500,
            'maxBitrate': 5000,
        },
        'Normal': {
            'resolution': '1080',
            'framerate': 40,
            'avgBitrate': 4500,
            'maxBitrate': 5500,
        },
        'Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 6000,
            'maxBitrate': 7000,
        },
        'Very Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 7500,
            'maxBitrate': 9000,
        },
    },
    '3rd': {
        'options': [
            'Low',
            'Normal',
            'Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '1080',
            'framerate': 40,
            'avgBitrate': 4000,
            'maxBitrate': 5500,
        },
        'Normal': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 5000,
            'maxBitrate': 6500,
        },
        'Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 6500,
            'maxBitrate': 8000,
        },
    },
    '1st': {
        'options': [
            'Low',
            'Normal',
            'Good',
        ],
        'default': 'Normal',
        'Low': {
            'resolution': '720',
            'framerate': 40,
            'avgBitrate': 4500,
            'maxBitrate': 5500,
        },
        'Normal': {
            'resolution': '720',
            'framerate': 60,
            'avgBitrate': 6000,
            'maxBitrate': 7500,
        },
        'Good': {
            'resolution': '1080',
            'framerate': 60,
            'avgBitrate': 8000,
            'maxBitrate': 9500,
        },
    },
};